n1=int(input("enter 1st no:\n"))
n2=int(input("enter 2nd no:\n"))
print("addition of",n1,"and",n2,"is:",n1+n2)
print("subtraction of",n1,"and",n2,"is:",n1-n2)
print("multiplication of",n1,"and",n2,"is:",n1*n2)
print("division of",n1,"and",n2,"is:",n1/n2)
print("power of",n1,"and",n2,"is:",n1**n2)
print("modulus of",n1,"and",n2,"is:",n1%n2)
print("floor division of",n1,"and",n2,"is:",n1//n2)