no1=int(input("enter 1st no:\n"))
no2=int(input("enter 2nd no:\n"))
print("bitwise AND operation between",no1,"and",no2,"is:",no1&no2)
print("bitwise OR operation between",no1,"and",no2,"is:",no1|no2)
print("bitwise NOT operation Of",no1,"is:",~no1)
print("bitwise NOT operation Of",no2,"is:",~no2)
print("bitwise XOR operation between",no1,"and",no2,"is:",no1^no2)
print("bitwise RIGHT SHIFT operation between",no1,"and",no2,"is:",no1>>no2)
print("bitwise LEFT SHIFT operation between",no1,"and",no2,"is:",no1<<no2)