name=input("enter your name:\n")
age=(input("enter your age:\n"))
gender=input("enter your gender:\n")
bplace=input("enter your birth place:\n")
mob=input("enter 10 digit phone no:\n")
print("NAME:",name)
print("AGE:",age)
print("Gender:",gender)
print("BIRTH PLACE:",bplace)
print("MOB:",mob)
