from tkinter import *
import tkinter.messagebox as MessageBox

root=Tk()
root.geometry("600x300")
root.title("python signup")
id=Label(root,text="Enter ID",font=("bold",10))
id.place(x=30,y=30)
name=Label(root,text="Enter Name",font=("bold",10))
name.place(x=30,y=50)
password=Label(root,text="Enter Password",font=("bold",10))
password.place(x=30,y=70)
e_id=Entry(bg="#DC143C")
e_id.place(x=140,y=30)
e_name=Entry(bg="#DC143C")
e_name.place(x=140,y=50)
e_password=Entry(bg="#DC143C")
e_password.place(x=140,y=70)
insert=Button(root,text="submit",font=("bold",10),bg="lightgreen",command=INSERT)
insert.place(x=30,y=150)
insert=Button(root,text="Delete",font=("bold",10),bg="lightgreen",command=INSERT)
insert.place(x=90,y=150)
insert=Button(root,text="Update",font=("bold",10),bg="lightgreen",command=INSERT)
insert.place(x=150,y=150)
root.mainloop()